[build]
  command = "REACT_APP_APP_VERSION=$COMMIT_REF npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  CI = "false"

[functions]
  directory = "netlify/functions"

